/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package henrique.loja_de_informatica.view;

import henrique.loja_de_informatica.dao.PersistenciaJPA;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Cliente;

/**
 *
 * @author henrique
 */
public class Tela_Cliente extends javax.swing.JFrame {
    PersistenciaJPA jpa;
    /**
     * Creates new form Tela_Cliente
     */
    public Tela_Cliente() {
        setTitle("Cliente");
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jpa = new PersistenciaJPA();
        carregarClienteCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Novo_Cliente = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        Remover_Cliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_Clientes = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        txtBusca_Nome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Novo_Cliente.setText("Novo");
        btn_Novo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Novo_ClienteActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        Remover_Cliente.setText("Remover");
        Remover_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_ClienteActionPerformed(evt);
            }
        });

        lista_Clientes.setToolTipText("");
        jScrollPane1.setViewportView(lista_Clientes);

        jLabel2.setText("Nome");

        txtBusca_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusca_NomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Novo_Cliente)
                        .addGap(28, 28, 28)
                        .addComponent(Remover_Cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusca_Nome))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBusca_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Novo_Cliente)
                    .addComponent(btnEditar)
                    .addComponent(Remover_Cliente))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Novo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Novo_ClienteActionPerformed
        Tela_Cadastro_Cliente telaCadastro
                = new Tela_Cadastro_Cliente(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);

        carregarClienteCadastrados();
    }//GEN-LAST:event_btn_Novo_ClienteActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Cliente cliente_selecionado = lista_Clientes.getSelectedValue();
        if (cliente_selecionado != null) {
            Tela_Cadastro_Cliente telaEdt = new Tela_Cadastro_Cliente(this, rootPaneCheckingEnabled);
            telaEdt.setCliente(cliente_selecionado);
            telaEdt.setVisible(true);
            
            
            carregarClienteCadastrados();
            
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void Remover_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_ClienteActionPerformed
        Cliente cliente_selecionado = lista_Clientes.getSelectedValue();
        if (cliente_selecionado != null) {
            System.out.println("Cliente: " + cliente_selecionado.getTipo_Cliente());
            try {
                jpa.conexaoAberta();

                int delOp = JOptionPane.showConfirmDialog(this,
                        "Tem certeza que deseja remover " + cliente_selecionado.getNome() + "?");
                if (delOp == JOptionPane.YES_OPTION) {
                    jpa.remover(cliente_selecionado);
                }

                jpa.fecharConexao();
                carregarClienteCadastrados();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao remover cliente " + cliente_selecionado + "\n" + e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma pessoa para remover");
        }
    }//GEN-LAST:event_Remover_ClienteActionPerformed

    private void txtBusca_NomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusca_NomeKeyReleased
        if(txtBusca_Nome.getText().trim().isEmpty()){
            carregarClienteCadastrados();
        } else{
            jpa.conexaoAberta();
            DefaultListModel modeloLista = new DefaultListModel();
            modeloLista.addAll(jpa.getClientes(txtBusca_Nome.getText().trim()));
            System.out.println("Pessoas carregadas: "+jpa.getClientes(txtBusca_Nome.getText().trim()));
            lista_Clientes.setModel(modeloLista);

            jpa.fecharConexao();
        }
    }//GEN-LAST:event_txtBusca_NomeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cliente().setVisible(true);
            }
        });
    }
    
    public void carregarClienteCadastrados() {
        jpa.conexaoAberta();

        DefaultListModel modeloLista = new DefaultListModel();
        modeloLista.addAll(jpa.getClientes());
        lista_Clientes.setModel(modeloLista);

        jpa.fecharConexao();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Remover_Cliente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btn_Novo_Cliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Cliente> lista_Clientes;
    private javax.swing.JTextField txtBusca_Nome;
    // End of variables declaration//GEN-END:variables
}
